# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 15:20
from __future__ import unicode_literals

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.ImageField(help_text='image url', storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to='')),
                ('point', models.ImageField(help_text='image url', storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to='')),
                ('men', models.ImageField(help_text='image url', storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to='')),
                ('wall', models.ImageField(help_text='image url', storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to='')),
                ('background', models.ImageField(help_text='image url', storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
