# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 17:04
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk_skins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skins',
            name='background',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='skins',
            name='box',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='skins',
            name='men',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='skins',
            name='point',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='skins',
            name='wall',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to=''),
        ),
    ]
