# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 15:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sk_game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sk_skins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False, help_text='object show for everyone or only for owner')),
                ('x', models.PositiveSmallIntegerField(help_text='position by x coordinate')),
                ('y', models.PositiveSmallIntegerField(help_text='position by y coordinate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False, help_text='object show for everyone or only for owner')),
                ('title', models.CharField(help_text='title of map', max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(related_name='players', through='sk_game.UserMapMembership', to=settings.AUTH_USER_MODEL)),
                ('skin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sk_skins.Skins')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Men',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False, help_text='object show for everyone or only for owner')),
                ('x', models.PositiveSmallIntegerField(help_text='position by x coordinate')),
                ('y', models.PositiveSmallIntegerField(help_text='position by y coordinate')),
                ('map', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sk_map.Map')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False, help_text='object show for everyone or only for owner')),
                ('x', models.PositiveSmallIntegerField(help_text='position by x coordinate')),
                ('y', models.PositiveSmallIntegerField(help_text='position by y coordinate')),
                ('map', models.ForeignKey(help_text='id of map that pointed', on_delete=django.db.models.deletion.CASCADE, to='sk_map.Map')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False, help_text='object show for everyone or only for owner')),
                ('x', models.PositiveSmallIntegerField(help_text='position by x coordinate')),
                ('y', models.PositiveSmallIntegerField(help_text='position by y coordinate')),
                ('map', models.ForeignKey(help_text='id of map that pointed', on_delete=django.db.models.deletion.CASCADE, to='sk_map.Map')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='box',
            name='map',
            field=models.ForeignKey(help_text='id of map that pointed', on_delete=django.db.models.deletion.CASCADE, to='sk_map.Map'),
        ),
        migrations.AddField(
            model_name='box',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='wall',
            unique_together=set([('x', 'y', 'map')]),
        ),
        migrations.AlterUniqueTogether(
            name='point',
            unique_together=set([('x', 'y', 'map')]),
        ),
        migrations.AlterUniqueTogether(
            name='box',
            unique_together=set([('x', 'y', 'map')]),
        ),
    ]
