# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='rating',
            field=models.IntegerField(help_text='summary rating of map', null=True),
        ),
    ]
