# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk_map', '0002_map_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'initial'), (1, 'ready'), (2, 'hidden'), (3, 'deleted')], default=0, help_text='status of object - initial / ready / hidden / deleted'),
        ),
        migrations.AddField(
            model_name='map',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'initial'), (1, 'ready'), (2, 'hidden'), (3, 'deleted')], default=0, help_text='status of object - initial / ready / hidden / deleted'),
        ),
        migrations.AddField(
            model_name='men',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'initial'), (1, 'ready'), (2, 'hidden'), (3, 'deleted')], default=0, help_text='status of object - initial / ready / hidden / deleted'),
        ),
        migrations.AddField(
            model_name='point',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'initial'), (1, 'ready'), (2, 'hidden'), (3, 'deleted')], default=0, help_text='status of object - initial / ready / hidden / deleted'),
        ),
        migrations.AddField(
            model_name='wall',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'initial'), (1, 'ready'), (2, 'hidden'), (3, 'deleted')], default=0, help_text='status of object - initial / ready / hidden / deleted'),
        ),
    ]
