# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk_map', '0003_auto_20160710_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='public',
        ),
        migrations.RemoveField(
            model_name='map',
            name='public',
        ),
        migrations.RemoveField(
            model_name='men',
            name='public',
        ),
        migrations.RemoveField(
            model_name='point',
            name='public',
        ),
        migrations.RemoveField(
            model_name='wall',
            name='public',
        ),
        migrations.AlterField(
            model_name='box',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'initial'), (1, 'ready / public'), (2, 'hidden / private'), (3, 'deleted')], default=0, help_text='status of object - initial / public / private / deleted'),
        ),
        migrations.AlterField(
            model_name='map',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'initial'), (1, 'ready / public'), (2, 'hidden / private'), (3, 'deleted')], default=0, help_text='status of object - initial / public / private / deleted'),
        ),
        migrations.AlterField(
            model_name='men',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'initial'), (1, 'ready / public'), (2, 'hidden / private'), (3, 'deleted')], default=0, help_text='status of object - initial / public / private / deleted'),
        ),
        migrations.AlterField(
            model_name='point',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'initial'), (1, 'ready / public'), (2, 'hidden / private'), (3, 'deleted')], default=0, help_text='status of object - initial / public / private / deleted'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'initial'), (1, 'ready / public'), (2, 'hidden / private'), (3, 'deleted')], default=0, help_text='status of object - initial / public / private / deleted'),
        ),
    ]
