# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 15:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMapMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.PositiveSmallIntegerField(blank=True, help_text="anyone can rate the public map, but only if it's done", null=True, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
                ('done', models.BooleanField(default=False, help_text='read_only field, will automatically set as True, if server receive correct solution from steps field')),
                ('steps', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='level solution, sent to server after game level was done, format: [{x: 1, y: 2}, {x: 3, y: 4}, etc]', null=True)),
            ],
        ),
    ]
