# Generated by Django 5.0.6 on 2024-06-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk_game', '0002_auto_20160623_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermapmembership',
            name='steps',
            field=models.JSONField(blank=True, help_text='level solution, sent to server after game level was done, format: [{x: 1, y: 2}, {x: 3, y: 4}, etc]', null=True),
        ),
    ]
